services:
  - type: web
    name: coinguard-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install --production
    startCommand: cd backend && NODE_ENV=production node app.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
